// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoStudio.Api.Data;

#nullable disable

namespace VideoStudio.Api.Migrations
{
    [DbContext(typeof(VideoStudioDbContext))]
    [Migration("20260526012807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoStudio.Api.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.AudioTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AudioTracks");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.FinalVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("FinalVideos");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Logline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.RenderJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputAudioPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputVideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ShotId");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("RenderJobs");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Order");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Shot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputAudioPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputVideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OutputPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SceneId", "Order");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Asset", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.AudioTrack", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany("AudioTracks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Character", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany("Characters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.FinalVideo", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithOne("FinalVideo")
                        .HasForeignKey("VideoStudio.Api.Domain.FinalVideo", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.RenderJob", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany("RenderJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoStudio.Api.Domain.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId");

                    b.HasOne("VideoStudio.Api.Domain.Shot", "Shot")
                        .WithMany("RenderJobs")
                        .HasForeignKey("ShotId");

                    b.Navigation("Project");

                    b.Navigation("Scene");

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Scene", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Shot", b =>
                {
                    b.HasOne("VideoStudio.Api.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VideoStudio.Api.Domain.Scene", "Scene")
                        .WithMany("Shots")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Project", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("AudioTracks");

                    b.Navigation("Characters");

                    b.Navigation("FinalVideo");

                    b.Navigation("RenderJobs");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Scene", b =>
                {
                    b.Navigation("Shots");
                });

            modelBuilder.Entity("VideoStudio.Api.Domain.Shot", b =>
                {
                    b.Navigation("RenderJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
